title: Patrick Driscoll # your name (or website title) here
logo: "images/IMG_8557 (2).JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br> I am a MS in Geography and Environmental Sustainability with a concentration in Geospatial Technologies grad from the University of Oklahoma and park ranger assistant with Sonoma County Parks.
  My current interests are in the fields of Environmental History, Parks and Recreation, Environmental Justice, and climate and fire studies. I am a member of the California Geographic Information Association and
  BayGeo. <br>

 # Links
  [More About Me](/About_Me.md)
  <a href="https://www.linkedin.com/in/patrick-driscoll-264108203">View My LinkedIn Profile</a>

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
